### ISSUE TITLE
how to use with koa1

### ISSUE THREAD

**Issue by zcc19910524** [keenondrums/cls-proxify#12]
i use with koa1 like this  but it only console 1
it seems clsProxifyKoaMiddleware is not worked
```
app.use(
    function *(next){
      console.log(1)
      clsProxifyKoaMiddleware(
         'clsKeyLogger',
         ctx => {
           console.log(2);
         }
       )
      yield next;
    }
  );
```

**Comment by fxlrnrpt** [comment]
@zcc19910524 the built-in middleware is for Koa v2. You could try building up the strategy outlined at https://github.com/aigoncharov/cls-proxify#any-other-framework-or-library or take a sneak peek at [cls-rtracer](https://github.com/puzpuzpuz/cls-rtracer/blob/master/src/rtracer.js#L166).
