### ISSUE TITLE
Fastify Plugin Decorators

### ISSUE THREAD

**Issue by brentsec** [keenondrums/cls-proxify#2]
Hello!

Your project looks awesome. Just out of curiosity, do you have any plans to add Fastify plugin decorators to it?

**Comment by fxlrnrpt** [comment]
@clarkbrent thank you! I do not have such plans yet.  To be honest, I haven't really used fastify much. Could you tell me what would be the advantage of using cls-proxify as a plugin decorator over using it as a middleware?
