### ISSUE TITLE
FR: provide namespace to use

### ISSUE THREAD

**Issue by ofer-papaya** [keenondrums/cls-proxify#3]
There are cases when the app already has a namespace and it would be very helpful to use the same namespace in cls proxify.

**Comment by fxlrnrpt** [comment]
@ofer-papaya what would be the use case? I mean my current thinking is that namespaces were introduced to provide an incapsulated environment for every library to avoid any conflicts. How using a dedicated namespace for cls-proxify is affecting your app? Namespaces should work together without any issues.

**Comment by ofer-papaya** [comment]
@keenondrums it might be an issue with `cls-hooked` but when we used multiple nested namespaces we got incorrect values so it looks like it's better to use a single namespace for the entire app. 
Providing the namespace has an additional value that it will decouple `cls-proxify` from `cls-hooked` and in case that there will be a new library as in the case that happened with `continuation-local-storage` and `cls-hooked` it will still be relevant.
